# Generated by Django 5.0.7 on 2024-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, help_text='Введите телеграм chat-id', max_length=100, null=True, verbose_name='Телеграм chat-id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите электронную почту', max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
