# Generated by Django 5.0.7 on 2024-08-06 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='publicity',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time_doing',
        ),
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=120), help_text='Введите предположительное время, в течении которого будете выполнять привычку', verbose_name='Время на выполнение привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Могут ли другие пользователи видеть эту привычку', verbose_name='Публичность'),
        ),
    ]
