# Generated by Django 5.0.7 on 2024-08-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_publicity_remove_habit_time_doing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_pleasurable',
            field=models.BooleanField(default=False, verbose_name='Признак приятной привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Укажите связанную привычку', null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.DeleteModel(
            name='RelatedHabit',
        ),
    ]
