# Generated by Django 5.0.7 on 2024-08-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_is_pleasurable_habit_related_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysofweek',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Могут ли другие пользователи видеть эту привычку', verbose_name='Признак публичности'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Привычка'),
        ),
    ]
