# Generated by Django 5.0.7 on 2024-08-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_daysofweek_habit_alter_habit_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='habit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Привычка'),
        ),
    ]
