# Generated by Django 5.0.7 on 2024-08-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_runtime_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysofweek',
            name='habit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Привычка'),
        ),
    ]
