# Generated by Django 5.0.7 on 2024-08-08 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_daysofweek_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=60), help_text='Введите предположительное время, в течении которого будете выполнять привычку', verbose_name='Время на выполнение привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Могут ли другие пользователи видеть эту привычку', verbose_name='Признак публичности'),
        ),
    ]
