# Generated by Django 5.0.7 on 2024-08-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_duration_alter_habit_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
    ]
