# Generated by Django 5.0.7 on 2024-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_remove_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysofweek',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='daysofweek',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='daysofweek',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='daysofweek',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='daysofweek',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='daysofweek',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='daysofweek',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Среда'),
        ),
    ]
